// Generated by CoffeeScript 1.6.2
var NoticiaM, User, _;

NoticiaM = require("../models/Noticias").NoticiasModelo;

User = require("../models/User").UsersModelo;

_ = require('underscore');

exports.noticias = function(req, res, next) {
  return NoticiaM.find({}, function(err, noticias) {
    if (!err) {
      console.log(noticias);
      return res.send({
        title: "pepe",
        status: 200,
        noticias: noticias
      });
    } else {
      return console.log(err);
    }
  });
};

exports.leer10 = function(req, res, next) {
  return NoticiaM.find({}, {}, {
    limit: 10
  }, function(err, noticias) {
    if (!err) {
      console.log(noticias);
      return res.render('index', {
        noticias: noticias
      });
    } else {
      return console.log(err);
    }
  });
};

exports.escribeloTodo = function(req, res, next) {
  var ejemplo;

  ejemplo = new NoticiaM({
    titulo: "Titulo1",
    descripcion: "Descripcion1",
    enlace: "http://www.google.es",
    fecha: "2015-01-01"
  });
  return ejemplo.save(function(err) {
    return res.render("index", {
      title: "Vladi"
    });
  });
};

exports.get = function(req, res, next) {
  return NoticiaM.find({}, function(err, noticias) {
    if (!err) {
      console.log(noticias);
      return res.render('panel/index', {
        noticias: noticias,
        user: req.session.user
      });
    } else {
      return console.log(err);
    }
  });
};

exports.post = function(req, res, next) {
  return User.findOne({
    _id: req.body.user_id
  }, function(err, user) {
    var noticia;

    if (!err) {
      console.log(user);
      noticia = new NoticiaM({
        titulo: req.body.titulo,
        descripcion: req.body.descripcion,
        enlace: req.body.enlace,
        fecha: Date.now(),
        owner_user: _.omit(user, 'passowrd')
      });
      noticia.save();
      return res.redirect('/panel/index');
    }
  });
};

exports.newform = function(req, res, next) {
  return res.render('panel/index', {
    user: req.session.user
  });
};
