// Generated by CoffeeScript 1.6.2
var mongoose, noticias, schema;

schema = require('mongoose').Schema;

mongoose = require('mongoose');

noticias = schema({
  titulo: {
    type: String,
    required: true
  },
  descripcion: {
    type: String,
    required: true
  },
  enlace: String,
  fecha: {
    type: Date,
    "default": Date.now
  },
  owner_user: {
    _id: String,
    email: String,
    name: String,
    surname: String,
    tel: String,
    street: String,
    locality: String
  }
});

exports.noticiasSchema = noticias;

exports.NoticiasModelo = mongoose.model('Noticias', noticias);
